# fly.toml app configuration file generated for customer-dashboard-beta on 2023-10-28T08:28:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-dashboard-beta"
primary_region = "bom"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]